services:
  - type: web
    name: ai-building-api
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: VWORLD_API_KEY
        sync: false
      - key: DATAGO_API_KEY
        sync: false
      - key: LAMBDA_PROXY_URL
        value: "https://3a9op0tcy6.execute-api.ap-northeast-2.amazonaws.com/prod/"
      - key: DATABASE_URL
        fromDatabase:
          name: ai-building-db
          property: connectionString

databases:
  - name: ai-building-db
    region: singapore
    plan: free
